app/urls.py
from django.urls import path
from . import views


app_name = 'app'

urlpatterns = [
    path('', views.MonthCalendar.as_view(), name='month_calendar'),
    path(
        'month/<int:year>/<int:month>/',
        views.MonthCalendar.as_view(),
        name='month_calendar_month',
    ),
    path(
        "create/<str:date>/",
        views.CreateSchedule.as_view(),
        name="create"
    ),
    path(
        "create/",
        views.CreateSchedule.as_view(),
        name="create_no_date"
    ),
    path(
        "update/<int:pk>/",
        views.UpdateSchedule.as_view(),
        name="update",
    ),
    path(
        'create_suggestion/',
        views.CreateSuggestion.as_view(),
        name='create_suggestion'
    ),
    path('week/', views.WeekCalendar.as_view(), name='week'),
    path(
        'week/<int:year>/<int:month>/<int:day>/',
        views.WeekCalendar.as_view(),
        name='week'
    ),
    path(
        'week_with_schedule/',
        views.WeekWithScheduleCalendar.as_view(),
        name='week_with_schedule'),
    path(
        'week_with_schedule/<int:year>/<int:month>/<int:day>/',
        views.WeekWithScheduleCalendar.as_view(),
        name='week_with_schedule'
    ),
    path('sample_day/', views.DayCalendar.as_view(), name='day'),
    path(
        'sample_day/<int:year>/<int:month>/<int:day>/',
        views.DayCalendar.as_view(),
        name='day'),
    path(
        'sample_day_schedule/',
        views.DayWithScheduleCalendar.as_view(),
        name='day_with_schedule'
    ),
    path(
        'sample_day_schedule/<int:year>/<int:month>/<int:day>/',
        views.DayWithScheduleCalendar.as_view(),
        name='day_with_schedule'
    ),

    path(
        "create/",
        views.CreateSchedule.as_view(),
        name="create"
    ),

    path(
        "update/<int:pk>",
        views.UpdateSchedule.as_view(),
        name="update",
    ),
    path(
        "delete/<int:pk>",
        views.DeleteSchedule.as_view(),
        name="delete"
    )


]

easy_calendar/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
import datetime
from django.db import models


class Suggestion(models.Model):
    """候補"""
    title = models.CharField('タイトル', max_length=50)
    memo = models.TextField('メモ', blank=True)
    start_time = models.TimeField('開始時刻', default=datetime.time(10, 0, 0))
    end_time = models.TimeField('終了時刻', default=datetime.time(10, 0, 0))
    is_confirmed = models.BooleanField('確定済み', default=True)

    class Meta:
        verbose_name = "候補"
        verbose_name_plural = "候補一覧"

    def __str__(self) -> str:
        return self.title


class Schedule(models.Model):
    """予定"""
    title = models.ForeignKey(
        Suggestion, verbose_name='タイトル', on_delete=models.PROTECT
    )
    memo = models.TextField('メモ', null=True, blank=True)
    start_time = models.TimeField('開始時刻', default=datetime.time(10, 0, 0))
    end_time = models.TimeField('終了時刻', default=datetime.time(10, 0, 0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', auto_now_add=True)
    is_confirmed = models.BooleanField('確定したか', default=True)

    def __str__(self) -> str:
        return f'{self.date}; {self.title}'

    class Meta:
        verbose_name = "予定"
        verbose_name_plural = "予定一覧"

app/templates/app/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    {% block extra_css %}{% endblock %}

    <title>カレンダー</title>
</head>
<body>

<header>
  <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app:month_calendar' %}">月カレンダー</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app:create_no_date' %}">予定を追加</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app:create_suggestion' %}">予定の候補を追加</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</header>

<div class="container" mt-3>
    {% block content %}{% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script> -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
{% block extrajs %}{% endblock %}
</body>
</html>

app/templates/app/create.html
{% extends 'app/base.html' %}
{% load static %}

{% block extra_css %}
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/create_schedule.css' %}">
{% endblock %}
<div class="col-sm-12">
    <label for="id_title" class="form-label">タイトル</label>
      {{form.title}}
      {{form.title.errors}}
  </div>

{% block content %}
<form action="" method="POST">
  {% csrf_token %}

  <div class="container">
    <h1 class="head">日程の追加</h1>
    <form action="" method="POST">
      {% csrf_token %}
      <div class="title">
        <label>タイトル</label>
        {{form.title}}
        {{form.title.errors}}
        <p>
            <!-- <a class="btn btn-danger" id="add_schedule" href="{% url 'app:create_suggestion' %}">予定の候補を追加</a> -->
            <a id="add_schedule" href="{% url 'app:create_suggestion' %}">予定の候補を追加</a>
        </p>
      </div>
      <div class="date">
        <label for="">日付</label>
        {{form.date}}
        {{form.date.errors}}
      </div>
      <div class="time">
        <div class="start">
            <label for="">開始時間:</label>
            {{form.start_time}}
            {{form.start_time.errors}}
        </div>
        <div class="end">
            <label for="">終了時間:</label>
            {{form.end_time}}
            {{form.end_time.errors}}
        </div>
      </div>
      <div class="memo">
        <p>詳細</p>
        {{form.memo}}
        {{form.memo.errors}}
      </div>
      <div class="is_confirmed">
        <label for="">確定</label>
        {{form.is_confirmed}}
        {{form.is_confirmed.errors}}
      </div>

  <button type="submit" name="next" value="confirm" class="btn btn-primary">日程の追加</button>

</form>
</div>
{% endblock content %}

{% block extrajs%}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
  <script>
      $(function () {
          let dateFormat = 'yy-mm-dd';
          $("#id_date").datepicker({
            dateFormat: dateFormat
          });
          $("#id_start_time").timeDropper({
              format: "H:mm",
              setCurrentTime: false,
          });
          $("#id_end_time").timeDropper({
              format: "H:mm",
              setCurrentTime: false,
          });
      });
  </script>
  <script>
    // 候補を選択したら他のフィールドにも値を設定
    const suggestions = JSON.parse('{{ suggestions_json|safe }}');
    const titleField = document.getElementById("id_title");

    titleField.addEventListener("change", function() {
      const chosenSuggestion = titleField.value;
      const chosen = suggestions.filter((item) => item.pk == chosenSuggestion)[0];
      document.getElementById("id_start_time").value = chosen.fields.start_time;
      document.getElementById("id_end_time").value = chosen.fields.end_time;
      document.getElementById("id_memo").value = chosen.fields.memo ?? chosen.fields.memo;
    });
  </script>
{% endblock %}

app/templates/app/create_alert.html
{% extends 'app/base.html' %}

{% block extra_css %}
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.min.css">
{% endblock %}

{% block content %}
<p>同じ時間に予定があります。<br>本当にこの予定を追加しますか？</p>


<form action="" method="POST">
  {% csrf_token %}

  {% for field in form %}
    {{ field.as_hidden }}
  {% endfor %}
  <button type="submit" name="next" value="create">追加する</button>
  <input type="button" value="戻る" onClick="javascript:history.go(-1);">

</form>

{% endblock content %}

{% block extrajs%}

{% endblock %}

app/templates/app/create_suggestion.html
{% extends 'app/base.html' %}
{% load static %}

{% block extra_css %}
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/create_suggestion.css' %}">
{% endblock %}

{% block content %}
<div class="form-container">
  <h1 class="col-sm-12 title">候補を追加</h1>
  <form action="" method="post">
    {% csrf_token %}
    <div class="col-sm-12">
      <label for="id_title" class="form-label">タイトル</label>
        {{form.title}}
        {{form.title.errors}}
    </div>
    <div class="col-sm-12 row">
      <div class="col-sm-4">
        <label for="id_start_time" class="form-label">開始時間</label>
        {{form.start_time}}
        {{form.start_time.errors}}
      </div>
      <div class="col-sm-4">
        <label for="id_end_time" class="form-label">終了時間</label>
        {{form.end_time}}
        {{form.end_time.errors}}
      </div>
    </div>
    <div class="col-sm-12">
      <label for="id_memo" class="form-label">詳細</label>
      {{form.memo}}
      {{form.memo.errors}}
    </div>
    <div class="col-sm-12">
      <button type="submit" class="btn btn-primary col-sm-5 submit-btn">追加する</button>
    </div>
  </form>

</div>
{% endblock content %}

{% block extrajs %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <script>
        $(function () {
            // timedropper
            $("#id_start_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
            $("#id_end_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
        });
    </script>
{% endblock %}

app/templates/app/day.html
{% extends 'app/base.html' %}
{% block content %}

    <a href="{% url 'app:day' day_previous.year day_previous.month  day_previous.day %}">{{ day_previous | date:"Y年m月d日" }}</a>
    <a href="{% url 'app:day' day_next.year day_next.month  day_next.day %}">{{ day_next | date:"Y年m月d日" }}</a>    

    <table border="1">
        <thead>
            <tr>
                <th colspan="2">The table header</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>The table body</td>
                <td>with two columns</td>
            </tr>
        </tbody>
    </table>
    <table class="table">
        <thead>
        <tr>
            <th>{{ current_week_name }}</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ current_day | date:"d" }}</td>
        </tr>
        </tbody>
    </table>
    
{% endblock %}

app/templates/app/day_with_schedule.html
{% extends 'app/base.html' %}
{% block content %}

    <a href="{% url 'app:day_with_schedule' day_previous.year day_previous.month  day_previous.day %}">{{ day_previous | date:"Y年m月d日" }}</a><!-- {{ day_previous | date:"Y年m月d日" }} -->
    <!--{{ current_day | date:"Y年m月d日" }}-->
    <a href="{% url 'app:day_with_schedule' day_next.year day_next.month  day_next.day %}">{{ day_next | date:"Y年m月d日" }}</a><!--{{ day_next | date:"Y年m月d日" }}-->
    <p style="text-align: right">
        <a href="{% url 'app:month_calendar_month' current_day.year current_day.month %}">月</a>
        /
        <a href="{% url 'app:week_with_schedule' current_day.year current_day.month current_day.day %}">週</a>
    </p>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th colspan="2">{{ current_day | date:"m月d日" }}({{ current_week_name }})</th>
            <a href="{% url 'app:create' day %}">予定を追加</a>
        </tr>
        </thead>
        <tbody>
        {% for schedule in schedule_list %}
            <tr>
                <td>
                    {{ schedule.start_time }} - {{ schedule.end_time }}
                </td>
                <td>
                    <a href="{% url 'app:update' schedule.pk %}">
                        {{ schedule.title }}
                      </a><br>
                    {{ schedule.memo }}<br>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    
{% endblock %}

app/templates/app/delete.html
{% extends "app/base.html" %}
{% block content %}
<p>削除しますか?</p>
<form method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="削除する">
    

</form>


{% endblock content %}

app/templates/app/month.html
{% extends 'app/base.html' %}
{% load static %}

{% block extra_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/month.css' %}">
{% endblock %}

{% block content %}
    <a href="{% url 'app:month_calendar_month' month_previous.year month_previous.month %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'app:month_calendar_month' month_next.year month_next.month %}">次月</a>

    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week in month_days %}
            <tr>
                {% for day in week %}
                    {% if now == day %}
                        <td class="today">
                            {% else %}
                        <td>
                    {% endif %}
                    <a href="{% url 'app:day_with_schedule' day.year day.month  day.day %}" class="today-url">

                {% if month_current.month != day.month %}
                    {{ day | date:"m/d" }}
                {% else %}
                    {{ day.day }}
                {% endif %}
              </a>

                {% for schedule in schedule_list %}
                  {% if schedule.date == day %}
                  <a href="{% url 'app:update' schedule.pk %}">
                    <div {% if schedule.is_confirmed %}class="schedule confirmed-schedule"{% else %}class="schedule non-confirmed-schedule"{% endif %}>
                      {{ schedule.title }}
                    </div>
                  </a>
                  {% endif %}
                {% endfor %}
                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/app/update.html
{% extends "app/base.html" %}
{% load static %}

{% block extra_css %}
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/update_schedule.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="head">日程の編集</h1>
    <form action="" method="POST">
      {% csrf_token %}
      <div class="title">
        <label>タイトル</label>
        {{form.title}}
      </div>
      <div class="date">
        <label for="">日付</label>
        {{form.date}}
      </div>
      <div class="time">
        <div class="start">
            <label for="">開始時間:</label>
            {{form.start_time}}
        </div>
        <div class="end">
            <label for="">終了時間:</label>
            {{form.end_time}}
        </div>
      </div>
      <div class="memo">
        <p>詳細</p>
        {{form.memo}}
      </div>
      <div class="is_confirmed">
        <label for="">確定</label>
        {{form.is_confirmed}}
      </div>

      <input class="btn btn-primary" type="submit" value="更新" >
      <a class = "btn btn-danger" href="{% url 'app:delete' pk %}" >削除</a>
    
    </form>
</div>
<!-- <form action="" method="POST">

    
    {% csrf_token %}

    <p id="title">タイトル</p>
    {{ form.title }}
    <p>メモ</p>
    {{ form.memo }}
    <p>日付</p>
    {{ form.date }}
    <p>開始時刻</p>
    {{ form.start_time }}
    <p>終了時刻</p>
    {{ form.end_time }}
    <p>確定してるか {{ form.is_confirmed }} </p>
    
    <input type="submit" value="更新">
    <a href="{% url 'app:delete' pk %}" >削除</a>

</form> -->


{% endblock content %}

app/templates/app/week.html
{% extends 'app/base.html' %}
{% block content %}

    <a href="{% url 'app:week' week_previous.year week_previous.month  week_previous.day %}">前週</a>
    {{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
    <a href="{% url 'app:week' week_next.year week_next.month  week_next.day %}">次週</a>

    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for day in week_days %}
                {% if now == day %}
                    <td class="table-success">
                        {% else %}
                    <td>
                {% endif %}
            {% if week_first.month != day.month %}
                {{ day | date:"m/d" }}
            {% else %}
                {{ day.day }}
            {% endif %}
            </td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
{% endblock %}

app/templates/app/week_with_schedule.html
{% extends 'app/base.html' %}
{% block content %}

    <a href="{% url 'app:week_with_schedule' week_previous.year week_previous.month  week_previous.day %}">前週</a>
    {{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
    <a href="{% url 'app:week_with_schedule' week_next.year week_next.month  week_next.day %}">次週</a>
    <p style="text-align: right">
        <a href="{% url 'app:month_calendar_month' week_first.year week_first.month %}">月</a>
    </p>

    
    <table class="table table-bordered">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for day in week_days %}
                {% if now == day %}
                    <td class="table-success">
                {% else %}
                    <td>
                {% endif %}
                <a href="{% url 'app:day_with_schedule' day.year day.month  day.day %}">
            {% if week_first.month != day.month %}
                {{ day | date:"m/d" }}
            {% else %}
                {{ day.day }}
            {% endif %}
            </a>
            </td>
            {% endfor %}
        </tr>
        <tr>
            {% for schedules in week_day_schedules.values %}
                <td>
                    {% for s in schedules %}
                        {{ s.title }}<br>
                        {{ s.start_time }} - {{ s.end_time }}<br>
                        {{ s.memo }}<br>
                        <br>
                    {% endfor %}
                </td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
{% endblock %}